// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import OnboardingController from "./onboarding_controller"
import IntegrationSetupController from "./integration_setup_controller"
import PollingController from "./polling_controller"
import SyncButtonController from "./sync_button_controller"
import GithubSettingsController from "./github_settings_controller"
import GeneratePrController from "./generate_pr_controller"
import PrAutoOpenController from "./pr_auto_open_controller"

application.register("hello", HelloController)
application.register("onboarding", OnboardingController)
application.register("integration-setup", IntegrationSetupController)
application.register("polling", PollingController)
application.register("sync-button", SyncButtonController)
application.register("github-settings", GithubSettingsController)
application.register("generate-pr", GeneratePrController)
application.register("pr-auto-open", PrAutoOpenController)
