export const HIGHLIGHT_COLORS = {
  YELLOW: '#FBBF24',
  GREEN: '#10B981',
  BLUE: '#3B82F6',
  PURPLE: '#8B5CF6',
  ORANGE: '#F59E0B',
  RED: '#EF4444',
  HOT_PINK: '#FF69B4',
} as const;

export const HIGHLIGHT_COLOR_NAMES = {
  [HIGHLIGHT_COLORS.YELLOW]: 'Yellow',
  [HIGHLIGHT_COLORS.GREEN]: 'Green',
  [HIGHLIGHT_COLORS.BLUE]: 'Blue',
  [HIGHLIGHT_COLORS.PURPLE]: 'Purple',
  [HIGHLIGHT_COLORS.ORANGE]: 'Orange',
  [HIGHLIGHT_COLORS.RED]: 'Red',
  [HIGHLIGHT_COLORS.HOT_PINK]: 'Hot Pink',
} as const;

export const HIGHLIGHT_COLOR_CONTRAST = {
  [HIGHLIGHT_COLORS.YELLOW]: '#1F2937',
  [HIGHLIGHT_COLORS.GREEN]: '#FFFFFF',
  [HIGHLIGHT_COLORS.BLUE]: '#FFFFFF',
  [HIGHLIGHT_COLORS.PURPLE]: '#FFFFFF',
  [HIGHLIGHT_COLORS.ORANGE]: '#1F2937',
  [HIGHLIGHT_COLORS.RED]: '#FFFFFF',
  [HIGHLIGHT_COLORS.HOT_PINK]: '#FFFFFF',
} as const;

export const HIGHLIGHT_COLOR_ARRAY = [
  { name: 'Yellow', value: HIGHLIGHT_COLORS.YELLOW, contrast: HIGHLIGHT_COLOR_CONTRAST[HIGHLIGHT_COLORS.YELLOW] },
  { name: 'Green', value: HIGHLIGHT_COLORS.GREEN, contrast: HIGHLIGHT_COLOR_CONTRAST[HIGHLIGHT_COLORS.GREEN] },
  { name: 'Blue', value: HIGHLIGHT_COLORS.BLUE, contrast: HIGHLIGHT_COLOR_CONTRAST[HIGHLIGHT_COLORS.BLUE] },
  { name: 'Purple', value: HIGHLIGHT_COLORS.PURPLE, contrast: HIGHLIGHT_COLOR_CONTRAST[HIGHLIGHT_COLORS.PURPLE] },
  { name: 'Orange', value: HIGHLIGHT_COLORS.ORANGE, contrast: HIGHLIGHT_COLOR_CONTRAST[HIGHLIGHT_COLORS.ORANGE] },
  { name: 'Red', value: HIGHLIGHT_COLORS.RED, contrast: HIGHLIGHT_COLOR_CONTRAST[HIGHLIGHT_COLORS.RED] },
  { name: 'Hot Pink', value: HIGHLIGHT_COLORS.HOT_PINK, contrast: HIGHLIGHT_COLOR_CONTRAST[HIGHLIGHT_COLORS.HOT_PINK] },
] as const;

export type HighlightColor = typeof HIGHLIGHT_COLORS[keyof typeof HIGHLIGHT_COLORS];