/**
 * GitHub PR creator — full 7-step workflow for creating PRs from ideas.
 * Ported from Rails PrCreator.
 */
import { eq } from "drizzle-orm";
import type { Database } from "@customer-pulse/db/client";
import { ideas, ideaPullRequests, integrations } from "@customer-pulse/db/client";
import { decryptCredentialsColumn } from "@customer-pulse/db/lockbox";
import { analyzeRepo } from "./repo-analyzer.js";
import { generateCode, type FileChange } from "./code-generator.js";

interface GithubCreds {
  access_token: string;
  owner: string;
  repo: string;
  default_branch?: string;
}

async function updateProgress(db: Database, prId: number, step: number, message: string) {
  await db.update(ideaPullRequests).set({
    progressStep: step,
    progressMessage: message,
    updatedAt: new Date(),
  }).where(eq(ideaPullRequests.id, prId));
}

export async function createPullRequest(
  db: Database,
  pullRequestId: number,
): Promise<void> {
  const [pr] = await db.select().from(ideaPullRequests).where(eq(ideaPullRequests.id, pullRequestId)).limit(1);
  if (!pr) throw new Error("Pull request record not found");

  const [idea] = await db.select().from(ideas).where(eq(ideas.id, pr.ideaId)).limit(1);
  if (!idea) throw new Error("Idea not found");

  const [integration] = await db.select().from(integrations).where(eq(integrations.id, pr.integrationId)).limit(1);
  if (!integration) throw new Error("GitHub integration not found");

  const masterKey = process.env.LOCKBOX_MASTER_KEY ?? "";
  const decrypted = decryptCredentialsColumn(integration.credentialsCiphertext, masterKey);
  const creds = JSON.parse(decrypted) as GithubCreds;
  const headers: Record<string, string> = {
    Authorization: `token ${creds.access_token}`,
    Accept: "application/vnd.github.v3+json",
    "Content-Type": "application/json",
  };
  const branch = creds.default_branch || "main";
  const owner = creds.owner;
  const repo = creds.repo;

  try {
    // Step 1: Analyze repo
    await updateProgress(db, pullRequestId, 1, "Analyzing repository...");
    const repoContext = await analyzeRepo(db, integration.id, creds);

    // Step 2: Generate code
    await updateProgress(db, pullRequestId, 2, "Generating code changes...");
    const hints = Array.isArray(idea.implementationHints) ? idea.implementationHints.map(String) : [];
    const codeResult = await generateCode(idea.title, idea.description, hints, repoContext);
    if (!codeResult || !codeResult.files?.length) {
      throw new Error("Code generation produced no files");
    }

    // Step 3: Review (validate changes aren't destructive)
    await updateProgress(db, pullRequestId, 3, "Reviewing generated code...");
    for (const file of codeResult.files) {
      if (file.action === "modify" && file.content.length < 10) {
        throw new Error(`Suspicious modification: ${file.path} has very little content`);
      }
    }

    // Step 4: Create branch
    await updateProgress(db, pullRequestId, 4, "Creating feature branch...");
    const branchName = `cp/idea-${idea.id}-${Date.now().toString(36)}`;

    // Get base branch ref
    const baseRefRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/ref/heads/${branch}`, { headers });
    if (!baseRefRes.ok) throw new Error(`Get base ref: HTTP ${baseRefRes.status}`);
    const baseRef = (await baseRefRes.json()) as { object?: { sha?: string } };
    const baseSha = baseRef.object?.sha;
    if (!baseSha) throw new Error("Could not get base branch SHA");

    // Create new branch
    const createRefRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs`, {
      method: "POST",
      headers,
      body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: baseSha }),
    });
    if (!createRefRes.ok) throw new Error(`Create branch: HTTP ${createRefRes.status}`);

    // Step 5: Commit files
    await updateProgress(db, pullRequestId, 5, "Committing files...");
    for (const file of codeResult.files) {
      await commitFile(headers, owner, repo, branchName, file, codeResult.commit_message);
    }

    // Step 6: Open PR
    await updateProgress(db, pullRequestId, 6, "Opening pull request...");
    const prBody = [
      `## ${idea.title}`,
      "",
      idea.description,
      "",
      `### Changes`,
      codeResult.summary,
      "",
      `### Files changed`,
      ...codeResult.files.map((f) => `- \`${f.path}\` (${f.action})`),
      "",
      "_Generated by Customer Pulse_",
    ].join("\n");

    const createPrRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        title: `[Customer Pulse] ${idea.title}`,
        body: prBody,
        head: branchName,
        base: branch,
      }),
    });
    if (!createPrRes.ok) {
      const errBody = await createPrRes.text();
      throw new Error(`Create PR: HTTP ${createPrRes.status} — ${errBody}`);
    }
    const prResult = (await createPrRes.json()) as { number?: number; html_url?: string };

    // Step 7: Complete
    await updateProgress(db, pullRequestId, 7, "Complete!");
    const now = new Date();
    await db.update(ideaPullRequests).set({
      status: 1, // open
      prNumber: prResult.number ?? null,
      prUrl: prResult.html_url ?? null,
      branchName,
      filesChanged: codeResult.files.map((f) => ({ path: f.path, action: f.action })) as unknown[],
      updatedAt: now,
    }).where(eq(ideaPullRequests.id, pullRequestId));

  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    await db.update(ideaPullRequests).set({
      status: 4, // failed
      errorMessage: msg,
      progressMessage: `Failed: ${msg}`,
      updatedAt: new Date(),
    }).where(eq(ideaPullRequests.id, pullRequestId));
    throw err;
  }
}

async function commitFile(
  headers: Record<string, string>,
  owner: string,
  repo: string,
  branch: string,
  file: FileChange,
  message: string,
): Promise<void> {
  // Get current file SHA if modifying
  let sha: string | undefined;
  if (file.action === "modify") {
    const getRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${file.path}?ref=${branch}`, { headers });
    if (getRes.ok) {
      const getJson = (await getRes.json()) as { sha?: string };
      sha = getJson.sha;
    }
  }

  const putRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${file.path}`, {
    method: "PUT",
    headers,
    body: JSON.stringify({
      message,
      content: Buffer.from(file.content).toString("base64"),
      branch,
      ...(sha ? { sha } : {}),
    }),
  });

  if (!putRes.ok) {
    const errBody = await putRes.text();
    throw new Error(`Commit ${file.path}: HTTP ${putRes.status} — ${errBody}`);
  }
}
