# frozen_string_literal: true

module Github
  class PrCreator
    def initialize(idea:, integration:)
      @idea = idea
      @integration = integration
      @client = Integrations::GithubClient.new(integration)
    end

    def create
      pull_request = @idea.idea_pull_requests.create!(
        integration: @integration,
        status: :pending
      )

      begin
        analysis_result = ensure_repo_analysis
        return failure(pull_request, analysis_result[:error]) unless analysis_result[:success]

        repo_analysis = analysis_result[:analysis]

        code_result = generate_code(repo_analysis)
        return failure(pull_request, code_result[:error]) unless code_result[:success]

        branch_name = generate_branch_name
        branch_result = @client.create_branch(branch_name)
        return failure(pull_request, branch_result[:error]) unless branch_result[:success]

        pull_request.update!(branch_name: branch_name)

        commit_result = commit_changes(code_result[:changes], branch_name, code_result[:commit_message])
        return failure(pull_request, commit_result[:error]) unless commit_result[:success]

        pr_result = create_pull_request(
          branch_name: branch_name,
          title: code_result[:pr_title],
          description: code_result[:pr_description]
        )
        return failure(pull_request, pr_result[:error]) unless pr_result[:success]

        pull_request.update!(
          status: :open,
          pr_number: pr_result[:pr_number],
          pr_url: pr_result[:pr_url],
          files_changed: code_result[:changes].map { |c| { path: c[:path], action: c[:action] } }
        )

        schedule_auto_merge(pull_request) if auto_merge_enabled?

        { success: true, pull_request: pull_request }
      rescue => e
        failure(pull_request, e.message)
      end
    end

    private

    def ensure_repo_analysis
      analyzer = Github::RepoAnalyzer.new(@integration)
      analyzer.analyze
    end

    def generate_code(repo_analysis)
      generator = Ai::CodeGenerator.new(integration: @integration)
      generator.generate(idea: @idea, repo_analysis: repo_analysis)
    end

    def generate_branch_name
      slug = @idea.title.parameterize.first(30)
      timestamp = Time.current.strftime("%Y%m%d%H%M%S")
      "customer-pulse/idea-#{@idea.id}-#{slug}-#{timestamp}"
    end

    def commit_changes(changes, branch_name, commit_message)
      changes.each do |change|
        case change[:action]
        when "create", "modify"
          existing_sha = nil

          if change[:action] == "modify"
            existing = @client.fetch_file_content(change[:path], ref: branch_name)
            existing_sha = existing[:sha] if existing[:success]
          end

          result = @client.create_or_update_file(
            change[:path],
            change[:content],
            "#{commit_message}\n\n#{change[:description]}",
            branch: branch_name,
            sha: existing_sha
          )

          return { success: false, error: result[:error] } unless result[:success]

        when "delete"
          Rails.logger.info("Skipping delete action for #{change[:path]} - not implemented")
        end
      end

      { success: true }
    rescue => e
      { success: false, error: e.message }
    end

    def create_pull_request(branch_name:, title:, description:)
      pr_body = <<~BODY
        ## Summary
        #{description}

        ---

        **Idea:** #{@idea.title}
        **Type:** #{@idea.idea_type.titleize}
        **Effort:** #{@idea.effort_estimate.titleize}
        **Impact:** #{@idea.impact_estimate.titleize}

        ---

        🤖 This PR was automatically generated by [Customer Pulse](https://github.com/your-org/customer-pulse) based on customer feedback analysis.
      BODY

      @client.create_pull_request(
        title: title,
        body: pr_body,
        head: branch_name
      )
    end

    def auto_merge_enabled?
      settings = Rails.cache.fetch("app_settings", expires_in: 1.hour) { {} }
      settings["github_auto_merge"] == true || settings["github_auto_merge"] == "true"
    end

    def schedule_auto_merge(pull_request)
      GithubAutoMergeJob.perform_in(5.minutes, pull_request.id)
    end

    def failure(pull_request, error_message)
      pull_request.update!(status: :failed, error_message: error_message)
      { success: false, error: error_message, pull_request: pull_request }
    end
  end
end
